# Generated by Django 4.1.1 on 2022-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travalo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destinations',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
